b_1-redefine_strcmp.c-1:
    file_name: "b_1-redefine_strcmp.c"
    cc: gcc-4.8
    opti_level: O2
    input: 
    check_type: 3
    test_str: "test   %rdi,%rdi"
    section_name: "<strcmp>:"
    special_cause: UB
    
b_1-redefine_strcmp.c-2:
    file_name: "b_1-redefine_strcmp.c"
    cc: gcc-7
    opti_level: O2
    input: 
    check_type: 3
    test_str: "test   %rdi,%rdi"
    section_name: "<strcmp>:"
    special_cause: UB
    
b_1-redefine_strcmp.c-3:
    file_name: "b_1-redefine_strcmp.c"
    cc: gcc-8
    opti_level: O1
    input: 
    check_type: 3
    test_str: "cmpq   $0x0,-0x8(%rbp)"
    section_name: "<strcmp>:"
    special_cause: UB
    
b_1-redefine_strcmp.c-4:
    file_name: "b_1-redefine_strcmp.c"
    cc: gcc-9
    opti_level: O1
    input: 
    check_type: 3
    test_str: "cmpq   $0x0"
    section_name: "<strcmp>:"
    special_cause: UB

b_1-redefine_strcmp.c-5:
    file_name: "b_1-redefine_strcmp.c"
    cc: gcc-7
    opti_level: O0
    input:
    check_type: 3
    test_str: "cmpq   $0x0"
    section_name: "<strcmp>:"
    special_cause: UB

b_1-redefine_strcmp.c-6:
    file_name: "b_1-redefine_strcmp.c"
    cc: gcc-4.8
    opti_level: O3
    input:
    check_type: 3
    test_str: "test   %rdi,%rdi"
    section_name: "<strcmp>:"

b_2-builtin_ctz.c-1:
    file_name: "b_2-builtin_ctz.c"
    cc: gcc-4.9
    opti_level: O2
    input: 0
    check_type: 1
    test_str: ok
    section_name: 
    
b_2-builtin_ctz.c-2:
    file_name: "b_2-builtin_ctz.c"
    cc: gcc-8
    opti_level: O1
    input: 0
    check_type: 1
    test_str: ok
    section_name: 
    
b_2-builtin_ctz.c-3:
    file_name: "b_2-builtin_ctz.c"
    cc: gcc-8
    opti_level: O2
    input: 0
    check_type: 1
    test_str: ok
    section_name:

b_2-builtin_ctz.c-4:
    file_name: "b_2-builtin_ctz.c"
    cc: gcc-4.9
    opti_level: O3
    input: 0
    check_type: 1
    test_str: ok
    section_name:

b_2-builtin_ctz.c-5:
    file_name: "b_2-builtin_ctz.c"
    cc: clang-3.9
    opti_level: O1
    input: 0
    check_type: 3
    test_str: "cmp"
    section_name: "<test>:"
    
b_3-strlen-oob.c-1:
    file_name: "b_3-strlen-oob.c"
    cc: gcc-8
    opti_level: O2
    input:
    check_type: 1
    test_str: ok
    section_name: 
    special_cause: UB

b_3-strlen-oob.c-2:
    file_name: "b_3-strlen-oob.c"
    cc: gcc-8
    opti_level: O0
    input:
    check_type: 1
    test_str: ok
    section_name:
    special_cause: UB

b_3-strlen-oob.c-3:
    file_name: "b_3-strlen-oob.c"
    cc: gcc-8
    opti_level: O3
    input:
    check_type: 1
    test_str: ok
    section_name:
    special_cause: UB

b_4-int_overflow.c-1:
    file_name: "b_4-int_overflow.c"
    cc: gcc-4.8
    opti_level: O2
    input: 2147483647
    check_type: 2
    test_str: ok
    section_name:
    specical_cause: UB

b_4-int_overflow.c-2:
    file_name: "b_4-int_overflow.c"
    cc: gcc-4.8
    opti_level: O0
    input: 2147483647
    check_type: 2
    test_str: ok
    section_name:
    specical_cause: UB

b_4-int_overflow.c-3:
    file_name: "b_4-int_overflow.c"
    cc: gcc-4.8
    opti_level: O3
    input: 2147483647
    check_type: 2
    test_str: ok
    section_name:
    specical_cause: UB

b_4-int_overflow.c-4:
    file_name: "b_4-int_overflow.c"
    cc: clang-3.9
    opti_level: O1
    input: 2147483647
    check_type: 2
    test_str: ok
    section_name:
    specical_cause: UB

b_5-ptr_sub_to_0.c-1:
    file_name: "b_5-ptr_sub_to_0.c"
    cc: clang-3.9
    opti_level: O1
    input:
    check_type: 1
    test_str: "check 0"
    section_name:
    special_cause: UB

b_5-ptr_sub_to_0.c-2:
    file_name: "b_5-ptr_sub_to_0.c"
    cc: gcc-9
    opti_level: O0
    input:
    check_type: 1
    test_str: "check 0"
    section_name:
    special_cause: UB

b_5-ptr_sub_to_0.c-3:
    file_name: "b_5-ptr_sub_to_0.c"
    cc: gcc-9
    opti_level: O1
    input:
    check_type: 1
    test_str: "check 0"
    section_name:
    special_cause: UB
    
b_6-modify_constPtr.c-1:
    file_name: "b_6-modify_constPtr.c"
    cc: gcc-8
    opti_level: O1
    input:
    check_type: 3
    test_str: "test"
    section_name: "<hello_start>:"
    special_cause: UB
    
b_6-modify_constPtr.c-2:
    file_name: "b_6-modify_constPtr.c"
    cc: gcc-8
    opti_level: O2
    input:
    check_type: 3
    test_str: "test"
    section_name: "<hello_start>:"
    special_cause: UB

b_6-modify_constPtr.c-3:
    file_name: "b_6-modify_constPtr.c"
    cc: gcc-8
    opti_level: O0
    input:
    check_type: 3
    test_str: "test"
    section_name: "<hello_start>:"
    special_cause: UB

b_6-modify_constPtr.c-4:
    file_name: "b_6-modify_constPtr.c"
    cc: gcc-5
    opti_level: O3
    input:
    check_type: 3
    test_str: "test"
    section_name: "<hello_start>:"
    special_cause: UB

b_6-modify_constPtr.c-5:
    file_name: "b_6-modify_constPtr.c"
    cc: gcc-5
    opti_level: O3
    input:
    check_type: 3
    test_str: "test"
    section_name: "<hello_start>:"
    special_cause: UB

b_6-modify_constPtr.c-6:
    file_name: "b_6-modify_constPtr.c"
    cc: clang-3.9
    opti_level: O1
    input:
    check_type: 3
    test_str: "test"
    section_name: "<hello_start>:"
    special_cause: UB

b_7-int_promotion.c-1:
    file_name: "b_7-int_promotion.c"
    cc: gcc-5
    opti_level: O2
    input: 255
    check_type: 3
    test_str: "%dil"
    section_name: "<test>:"
    special_cause: DB

b_7-int_promotion.c-2:
    file_name: "b_7-int_promotion.c"
    cc: gcc-5
    opti_level: O0
    input: 255
    check_type: 3
    test_str: "cmp    $0xffffffff"
    section_name: "<test>:"
    special_cause: DB

b_7-int_promotion.c-3:
    file_name: "b_7-int_promotion.c"
    cc: clang-3.9
    opti_level: O1
    input: 255
    check_type: 3
    test_str: "%dil"
    section_name: "<test>:"
    special_cause: DB

b_7-int_promotion.c-4:
    file_name: "b_7-int_promotion.c"
    cc: gcc-5
    opti_level: O3
    input: 255
    check_type: 3
    test_str: "%dil"
    section_name: "<test>:"
    special_cause: DB
    
b_8.c-1:
    file_name: "b_8.c"
    cc: gcc-5
    opti_level: O2
    input: 0
    check_type: 3
    test_str: "test"
    section_name: "<bad_code>:"
    special_cause: UB

b_8.c-2:
    file_name: "b_8.c"
    cc: gcc-8
    opti_level: O2
    input: 0
    check_type: 3
    test_str: "test"
    section_name: "<bad_code>:"
    special_cause: UB

b_8.c-3:
    file_name: "b_8.c"
    cc: gcc-8
    opti_level: O3
    input: 0
    check_type: 3
    test_str: "test"
    section_name: "<bad_code>:"
    special_cause: UB
    
b_9.c-1:
    file_name: "b_9.c"
    cc: gcc-4.8
    opti_level: O2
    input: 0
    check_type: 2
    test_str: "ok"
    section_name:
    special_cause: UB

b_9.c-2:
    file_name: "b_9.c"
    cc: gcc-4.8
    opti_level: O3
    input: 0
    check_type: 2
    test_str: "ok"
    section_name:
    special_cause: UB
    
b_10.c-1:
    file_name: "b_10.c"
    cc: gcc-4.4
    opti_level: O2
    input: 0
    check_type: 3
    test_str: "cmp"
    section_name: "<main>:"
    special_cause: UB
    
b_10.c-2:
    file_name: "b_10.c"
    cc: gcc-8
    opti_level: O1
    input: 0
    check_type: 3
    test_str: "cmp"
    section_name: "<main>:"
    special_cause: UB
    
b_10.c-3:
    file_name: "b_10.c"
    cc: gcc-4.8
    opti_level: O1
    input: 0
    check_type: 3
    test_str: "cmp"
    section_name: "<main>:"
    
b_10.c-4:
    file_name: "b_10.c"
    cc: gcc-8
    opti_level: O2
    input: 0
    check_type: 3
    test_str: "cmp"
    section_name: "<main>:"
    special_cause: UB

b_10.c-5:
    file_name: "b_10.c"
    cc: gcc-4.8
    opti_level: O3
    input: 0
    check_type: 3
    test_str: "cmp"
    section_name: "<main>:"
    special_cause: UB
    
b_11_for_loop.c-1:
    file_name: "b_11_for_loop.c"
    cc: gcc-4.8
    opti_level: O2
    input:
    check_type: 3
    test_str: "cmp    $0xa"
    section_name: "<main>:"
    special_cause: UB

b_11_for_loop.c-2:
    file_name: "b_11_for_loop.c"
    cc: gcc-4.8
    opti_level: O3
    input:
    check_type: 3
    test_str: "cmp    $0xa"
    section_name: "<main>:"
    special_cause: UB

b_12.c-1:
    file_name: "b_12.c"
    cc: clang-3.9
    opti_level: O1
    input:
    check_type: 6
    test_str: "jmp\t.LBB1_1"
    section_name: ".LBB1_1:"
    default_option: "-pthread"
    special_cause: UB

b_12.c-2:
    file_name: "b_12.c"
    cc: gcc-4.9
    opti_level: O3
    input:
    check_type: 6
    test_str: "jmp\t.L6"
    section_name: ".L6:"
    default_option: "-pthread"
    special_cause: UB

b_12.c-3:
    file_name: "b_12.c"
    cc: gcc-4.9
    opti_level: O2
    input:
    check_type: 6
    test_str: "jl\t.L3"
    section_name: ".L3:"
    default_option: "-pthread"
    special_cause: UB

b_13.c-1:
    file_name: "b_13.c"
    cc: gcc-7
    opti_level: O2
    input:
    check_type: 3
    test_str: "movl   $0x0"
    section_name: "between 0x4( 0xc("
    specical_cause: UB

b_13.c-2:
    file_name: "b_13.c"
    cc: gcc-7
    opti_level: O2
    input:
    check_type: 3
    test_str: "movl   $0x0"
    section_name: "between 0x4( 0xc("
    specical_cause: UB


b_14-printf_null.c-1:
    file_name: "b_14-printf_null.c"
    cc: gcc-7
    opti_level: O0
    input:
    check_type: 4
    test_str: "puts"
    section_name: "<main>:"
    specical_cause: UB

b_14-printf_null.c-2:
    file_name: "b_14-printf_null.c"
    cc: clang
    opti_level: O1
    input:
    check_type: 4
    test_str: "puts"
    section_name: "<main>:"
    specical_cause: UB

b_15.c-0:
    file_name: "b_15.c"
    cc: gcc
    opti_level: O2
    input:
    check_type: 4
    test_str: "call   11b0 <memset>"
    section_name: "<memset>:"
    specical_cause: UB

b_15.c-1:
    file_name: "b_15.c"
    cc: clang
    opti_level: O1
    input:
    check_type: 4
    test_str: "call   1160 <memset>"
    section_name: "<memset>:"
    specical_cause: UB

b_16.c-0:
    file_name: "b_16.c"
    cc: gcc
    opti_level: O2
    input:
    check_type: 1
    test_str: "80 70 60 50 40 30 88 77 66 55 44 33"
    section_name:
    specical_cause: UB

b_20.c-1:
    file_name: "b_20.c"
    cc: gcc-4.4
    opti_level: O1
    input:
    check_type: 7
    test_str: "panic"
    section_name: "%dil"
    specical_cause: UB
    
b_20.c-2:
    file_name: "b_20.c"
    cc: gcc-4.4
    opti_level: O2
    input:
    check_type: 7
    test_str: "panic"
    section_name: "%dil"
    specical_cause: UB

b_20.c-3:
    file_name: "b_20.c"
    cc: gcc-4.4
    opti_level: O3
    input:
    check_type: 7
    test_str: "panic"
    section_name: "%dil"
    specical_cause: UB

b_21-dse_memset.c-1:
    file_name: "b_21-dse_memset.c"
    cc: gcc-5
    opti_level: O1
    input:
    check_type: 3
    test_str: "memset"
    section_name: "<main>:"
    specical_cause: "Others"
    
b_21-dse_memset.c-2:
    file_name: "b_21-dse_memset.c"
    cc: gcc-5
    opti_level: O2
    input:
    check_type: 3
    test_str: "memset"
    section_name: "<main>:"
    specical_cause: "Others"

b_21-dse_memset.c-3:
    file_name: "b_21-dse_memset.c"
    cc: gcc-5
    opti_level: O3
    input:
    check_type: 3
    test_str: "memset"
    section_name: "<main>:"
    specical_cause: "Others"
    
b_21-dse_memset.c-4:
    file_name: "b_21-dse_memset.c"
    cc: clang-3.9
    opti_level: O1
    input:
    check_type: 3
    test_str: "memset"
    section_name: "<main>:"
    specical_cause: "Others"
    
b_22.c-1:
    file_name: "b_22.c"
    cc: gcc
    opti_level: O0
    input:
    check_type: 3
    test_str: "movl   $0x0"
    section_name: "movl   $0x0"
    specical_cause: "Others"

b_22.c-2:
    file_name: "b_22.c"
    cc: clang-3.9
    opti_level: O0
    input:
    check_type: 3
    test_str: "movl   $0x0"
    section_name: "movl   $0x0"
    specical_cause: "Others"

l_2.c-0:
    file_name: "l_2.c"
    cc: clang
    opti_level: O1
    input:
    check_type: 2
    test_str: "0"
    section_name:
    specical_cause: UB

l_6.c-1:
    file_name: "l_6.c"
    cc: gcc-7
    opti_level: O2
    input:
    check_type: 3
    test_str: "memcmp"
    section_name: "<main>:"
    
l_6.c-2:
    file_name: "l_6.c"
    cc: clang
    opti_level: O1
    input:
    check_type: 3
    test_str: "memcmp"
    section_name: "<main>:"

l_6.c-3:
    file_name: "l_6.c"
    cc: gcc-7
    opti_level: O3
    input:
    check_type: 3
    test_str: "memcmp"
    section_name: "<main>:"
    
l_8-oversized_shift.c-1:
    file_name: "l_8-oversized_shift.c"
    cc: clang-3.9
    opti_level: O1
    input:
    check_type: 3
    test_str: "cmpl   $0x0,"
    section_name: "<main>:"
    special_cause: UB

l_11.c-1:
    file_name: "l_11.c"
    cc: clang-3.9
    opti_level: O0
    input:
    check_type: 2
    test_str: "16"
    section_name:
    specical_cause: "Others"

l_11.c-2:
    file_name: "l_11.c"
    cc: gcc
    opti_level: O0
    input:
    check_type: 2
    test_str: "16"
    section_name:
    specical_cause: "Others"

l_13.c-1:
    file_name: "l_13.c"
    cc: gcc-9
    opti_level: O1
    input:
    check_type: 1
    test_str: "ok"
    section_name:
    special_cause: UB
    
l_13.c-2:
    file_name: "l_13.c"
    cc: gcc-9
    opti_level: O2
    input:
    check_type: 1
    test_str: "ok"
    section_name:
    special_cause: UB

l_13.c-3:
    file_name: "l_13.c"
    cc: gcc-9
    opti_level: O3
    input:
    check_type: 1
    test_str: "ok"
    section_name:
    special_cause: UB

l_15.c-1:
    file_name: "l_15.c"
    cc: gcc-4.9
    opti_level: O1
    input:
    check_type: 3
    test_str: "memset"
    section_name: "<main>:"
    special_cause: DB

l_15.c-2:
    file_name: "l_15.c"
    cc: gcc-4.9
    opti_level: O3
    input:
    check_type: 3
    test_str: "memset"
    section_name: "<main>:"

l_15.c-3:
    file_name: "l_15.c"
    cc: clang-3.9
    opti_level: O1
    input:
    check_type: 3
    test_str: "memset"
    section_name: "<main>:"

# l_16.c-0:
#     //TODO
#     special_cause: UB


l_18.c-1:
    file_name: "l_18.c"
    cc: clang-3.9
    opti_level: O0
    input:
    check_type: 4
    test_str: "memset"
    section_name: "<foo>:"
    specical_cause: "Environment assumption"

l_18.c-2:
    file_name: "l_18.c"
    cc: gcc-11
    opti_level: O0
    input:
    check_type: 4
    test_str: "memset"
    section_name: "<foo>:"
    specical_cause: "Environment assumption"

l_19.c-1:
    file_name: "l_19.c"
    cc: gcc-4.9
    opti_level: O2
    input:
    check_type: 1
    test_str: "ok"
    section_name:
    special_cause: DB

l_24.c-1:
    file_name: "l_24.c"
    cc: gcc-4.8
    opti_level: O2
    input:
    check_type: 3
    test_str: "test"
    section_name: "<main>:"
    special_cause: UB

l_24.c-2:
    file_name: "l_24.c"
    cc: gcc-4.8
    opti_level: O3
    input:
    check_type: 3
    test_str: "test"
    section_name: "<main>:"
    special_cause: UB

l_30.c-1:
    file_name: "l_30.c"
    cc: gcc
    opti_level: O1
    input:
    check_type: 2
    test_str: "101 102"
    section_name:
    default_option: "-m32 -pthread"
    special_cause: UB

l_30.c-2:
    file_name: "l_30.c"
    cc: clang-3.9
    opti_level: O1
    input:
    check_type: 2
    test_str: "101 102"
    section_name:
    default_option: "-m32 -pthread"
    special_cause: UB

l_37.c-1:
    file_name: "l_37.c"
    cc: gcc-4.8
    opti_level: O2
    input:
    check_type: 3
    test_str: "sub"
    section_name: "<main>:"
    specical_cause: "Others"

l_37.c-2:
    file_name: "l_37.c"
    cc: gcc-4.8
    opti_level: O1
    input:
    check_type: 3
    test_str: "sub"
    section_name: "<main>:"
    specical_cause: "Others"

l_37.c-3:
    file_name: "l_37.c"
    cc: gcc-4.8
    opti_level: O3
    input:
    check_type: 3
    test_str: "sub"
    section_name: "<main>:"
    specical_cause: "Others"

l_37.c-4:
    file_name: "l_37.c"
    cc: gcc-4.8
    opti_level: O0
    input:
    check_type: 3
    test_str: "addl   $0x1"
    section_name: "<main>:"
    specical_cause: "Others"

l_41.c-1:
    file_name: "l_41.c"
    cc: gcc-5
    opti_level: O1
    input:
    check_type: 5
    test_str: "call\thave_cpuid_p"
    section_name: "between call\tfoo2 puts"
    default_option: "-m32"
    specical_cause: "Environment assumption"

l_41.c-2:
    file_name: "l_41.c"
    cc: gcc-5
    opti_level: O2
    input:
    check_type: 5
    test_str: "call\thave_cpuid_p"
    section_name: "between call\tfoo2 puts"
    default_option: "-m32"
    specical_cause: "Environment assumption"

l_41.c-3:
    file_name: "l_41.c"
    cc: gcc-5
    opti_level: O3
    input:
    check_type: 5
    test_str: "call\thave_cpuid_p"
    section_name: "between call\tfoo2 puts"
    default_option: "-m32"
    specical_cause: "Environment assumption"

l_43.c-1:
    file_name: "l_43.c"
    cc: clang-3.9
    opti_level: O1
    input:
    check_type: 4
    test_str: "memset"
    section_name: "<main>:"
    special_cause: "Environment assumption"